application: bad-robot
version: x
runtime: python
api_version: 1

derived_file_type:
- python_precompiled

handlers:
- url: /static
  static_dir: static
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /opera/snapshot/check
  script: do_opera.py
  login: admin
- url: /opera/snapshot/cleanup
  script: do_opera.py
  login: admin
- url: /opera/.*
  script: do_opera.py
- url: .*
  script: main.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?\.gitignore
- ^(.*/)?\.git/